### ISSUE TITLE
Error when update text animation when a player is quitting

### ISSUE THREAD

**Issue by krzysiekigry** [CatCoderr/ProtocolSidebar#51]
java.lang.RuntimeException: An error occurred while updating sidebar for player: rafalino132
        at me.catcoder.sidebar.Sidebar.broadcast(Sidebar.java:459) ~[?:?]
        at me.catcoder.sidebar.Sidebar.updateLine(Sidebar.java:312) ~[?:?]
        at me.catcoder.sidebar.SidebarLine.lambda$updatePeriodically$0(SidebarLine.java:59) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[unknown]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[unknown]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[unknown]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: net.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information.
        §9☄ §fdc.mine_
        ^^

        ProtocolSidebar.newMiniMessageSidebar
        
        TextIterator discordAnimation = TextIterators.textTyping("www.minestar.pl", "_", 1, 5);
        SidebarLine<String> discord = page1.addUpdatableLine(player -> "<color:#8f0555>✉ <color:#FFFFFF>" + page1.toLineUpdater(discordAnimation).apply(player));
        discord.updatePeriodically(1, 5, page1);

**Comment by krzysiekigry** [comment]
I found the cause ViaVersion return -1 https://github.com/ViaVersion/ViaVersion/blob/master/api/src/main/java/com/viaversion/viaversion/api/ViaAPI.java#L91
[15:00:23 INFO]: clientVersion: 756
[15:00:23 INFO]: clientVersion: -1
[15:00:23 INFO]: Krzysiekigry lost connection [DISCONNECT]: Disconnected
