### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Natfan** [CatCoderr/ProtocolSidebar#78]
Hi there, I've encountered a bug while updating to 1.20.6 (to be honest, I've had to do a lot of version juggling with this upgrade but I'm close to being done). While I don't _rely_ on this library, it does make data stored in my application easily accessible to my users. 

For reference I use maven ([pom.xml](https://gist.github.com/Natfan/282b163b8293a8f7b6cb94a2e25b3905)), when I used v6.2.4 I got kicked for a similar error to xxx (io.netty.handler.codec.decoderexception: Failed to decode packet 'clientbound/minecraft:set_entity_data'), whereas now I just get the following error in my server console when attempting to execute `Sidebar<Component>#addViewer(@NotNull Player player)`:

```txt
[18:58:59 ERROR]: Could not pass event PlayerJoinEvent to myPlugin v1.0.0-SNAPSHOT
java.lang.NoClassDefFoundError: com/github/steveice10/opennbt/tag/builtin/Tag
        at myPlugin-1.0-SNAPSHOT.jar/me.catcoder.sidebar.util.buffer.ByteBufNetOutput.writeComponent(ByteBufNetOutput.java:34) ~[myPlugin-1.0-SNAPSHOT.jar:?]
        at myPlugin-1.0-SNAPSHOT.jar/me.catcoder.sidebar.ScoreboardObjective.getPacket(ScoreboardObjective.java:122) ~[myPlugin-1.0-SNAPSHOT.jar:?]
        at myPlugin-1.0-SNAPSHOT.jar/me.catcoder.sidebar.ScoreboardObjective.create(ScoreboardObjective.java:79) ~[myPlugin-1.0-SNAPSHOT.jar:?]
        at myPlugin-1.0-SNAPSHOT.jar/me.catcoder.sidebar.Sidebar.addViewer(Sidebar.java:396) ~[myPlugin-1.0-SNAPSHOT.jar:?]
        at myPlugin-1.0-SNAPSHOT.jar/com.example.myPlugin.NSidebar.showSidebar(NSidebar.java:122) ~[myPlugin-1.0-SNAPSHOT.jar:?]
        at myPlugin-1.0-SNAPSHOT.jar/com.example.myPlugin.listeners.PlayerJoinListener.onPlayerJoin(PlayerJoinListener.java:75) ~[myPlugin-1.0-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor186.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-147-e41d44f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:153) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.github.steveice10.opennbt.tag.builtin.Tag
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 31 more
```

It seems like the error is a dependency issue, where com/github/steveice10/opennbt isn't registered in my classpath. I haven't yet looked into this library, and will attempt to install it/shade it in soon to resolve the fault, but I was wondering if this was an issue that might be able to be resolved upstream?

Thanks for creating this library, by the way. Before this update I haven't had any issues, and developing with the library was (is? 😄) a breeze!

-nat

**Comment by CatCoderr** [comment]
Hello. Thank you for the positive feedback!

At the moment, I am busy with other tasks and am dedicating little time to this project. I will soon add a solution so that the necessary dependencies are embedded in the artifact. As you mentioned, you can manually add this library to your classpath. Additionally, you can install the latest version of ViaVersion on the server – this should also fix the issue.
